Feature/header
S-OSTeam/shop-web pull request #15
Opened 2024-02-02 10:34 UTC by KimEuiSoo

feature: 커스텀 hook 구현
 => login(test) 및 구현
 => 맥주소 라이브러리 미적용
 design: header 디자인

2024-02-03 05:20 UTC, Hangeulkim requested changes

2024-02-03 05:20 UTC, Hangeulkim commented on src/components/layout/header/Header.tsx
> +    const isInTablet = useMediaQuery('(max-width: 1024px)');
이런거 걍 전역에서 atom으로 관리하는게 낫지 않음?

2024-02-03 05:20 UTC, Hangeulkim commented on src/components/layout/header/category/CategoryHeader.tsx
> +        const currentState = tglState[idx];
Tgl은 뭐임...?

2024-02-03 05:20 UTC, Hangeulkim commented on src/components/layout/header/category/CategoryHeader.tsx
> +import clsN from 'classnames';
굳이 cn으로 안하고 clsn으로 한 이유는?

2024-02-03 05:20 UTC, Hangeulkim commented on src/components/layout/header/category/listItem/ListItem.tsx
> +    return (<>
이거 쓰지마 div나 box 달으랬잖아...

2024-02-03 05:20 UTC, Hangeulkim commented on src/components/layout/header/category/styles/CategoryHeader.module.scss
> +        .list_item_icon{
이런거 다 size로 하기로 한거 아녔음?

2024-02-03 05:20 UTC, Hangeulkim commented on src/components/layout/header/category/styles/CategoryHeader.module.scss
> +@include tablet {
어차피 %로 잡을거면 필요 없지 않음?

2024-02-03 05:20 UTC, Hangeulkim commented on src/components/layout/header/gnb/gnbMain/GnbMain.tsx
> +                    'Authorization-Mac': '00-A5-54-E3-83-AC',
Mac은 :으로 구분합니다

2024-02-03 05:20 UTC, Hangeulkim commented on src/components/layout/header/gnb/listItem/rightMenu/RightMenu.tsx
> +    gnb_r_ClsN?: string;
스네이크 쓸꺼면 스네이크만 쓰고 카멜쓸꺼면 카멜만써 이게 뭔 개판이여

2024-02-03 05:20 UTC, Hangeulkim commented on src/styles/scss/header/nav/Nav.ts
> +            background: blue[400],
이따구로 쓰지 말고 글로별 변수로 쓰라고!!!!!!

2024-02-03 05:53 UTC, Noma9363 reviewed
스네이크가 아닌 카멜 문법으로 수정하기

스타일에 쓰일 폰트, 이미지크기, 색, 브레이킹 포인트 고민하기

useMediaQuery 함수 사용 시 화면은 하나밖에 없으므로 아톰을 활용하여 전역으로 처리

헤더만 사용한다 하더라도 재활용성을 할 수 있을지 체크하기

반응형 화면 크기의 변환 시 역동적인 애니메이션 효과 생각해보기
[MuiTranstion](https://mui.com/material-ui/transitions/)

2024-02-03 05:53 UTC, Noma9363 commented on src/components/layout/header/gnb/gnbMain/GnbMain.tsx
> +    const isInTablet = useMediaQuery('(max-width: 1024px)');
Hangule 이 말한대로 Atom으로 관리

2024-02-03 05:53 UTC, Noma9363 commented on src/components/molecules/button/iconButton/IconButton.tsx
> +import {IconButton as MuiIconButton, IconButtonProps as MuiIconButtonProps} from '@mui/material';
원본 컴포넌트 구분하기 위해 as 를 사용함,

별칭 헷갈리는 경우를 방지하기 위해 사용

2024-02-03 05:53 UTC, Noma9363 commented on src/components/molecules/button/iconButton/IconButton.tsx
> +export interface IconBtnProps extends MuiIconButtonProps{
파생된 컴포넌트를 제작 시 혹시나 정의하지 못한 속성들이 존재 할 수 있으므로 

extends 처리

2024-02-03 05:53 UTC, Noma9363 commented on src/components/molecules/button/iconButton/IconButton.tsx
>  };
이미 Mui 에서 <IconButton/> 을 제공하고 있고 안정성과 공식 문서가 적혀있으므로 해당 컴포넌트를 사용

[Mui IconButton](https://mui.com/material-ui/api/icon-button/)

2024-02-03 05:53 UTC, Noma9363 commented on src/index.tsx
> +    <StyledEngineProvider injectFirst>
Mui 의 스타일처리로 인해 외부 스타일 오버드라이브가 거절되었음

해당 <StyledEngineProvider injectFirst> 태그 그리고 태그 속성 내 'injectFirst' 를 선언하면 
외부 스타일 오버라이딩을 할 수 있다.

2024-02-03 05:53 UTC, Noma9363 commented on src/styles/scss/header/nav/Nav.ts
> +            background: blue[400],
테마나 styled 컴포넌트 활용하지 않고

css-module 스타일 적용하는 방식으로

2024-02-03 05:53 UTC, Noma9363 commented on src/styles/scss/variables/mixin.scss
> +@import 'variables';
같은 루트에 있으므로 경로단축

2024-02-03 05:55 UTC, Noma9363 commented on src/components/layout/header/category/listItem/ListItem.tsx
> +    return (<>
리액트 프래그먼트나 다른 방향을 찾것습니다.

2024-02-03 05:56 UTC, Noma9363 commented on src/components/layout/header/category/CategoryHeader.tsx
> +import clsN from 'classnames';
??? : cn은 뭔 중국이름같냐 딴거없어?

2024-02-03 06:01 UTC, Noma9363 commented on src/components/layout/header/category/styles/CategoryHeader.module.scss
> +@include tablet {
width: min(n, n); 
을 사용시 부모의 크기에 따라 해당 속성의 패딩이 늘어나는 방법을 활용하여 
잉여 브레이킹 포인트가 줄여들 수 있는지 확인해 보겠음.

2024-02-03 06:01 UTC, Noma9363 commented on src/components/layout/header/gnb/listItem/rightMenu/RightMenu.tsx
> +    gnb_r_ClsN?: string;
죄송합니다...!

2024-02-03 06:02 UTC, Noma9363 commented on src/components/layout/header/category/CategoryHeader.tsx
> +        const currentState = tglState[idx];
토글

2024-02-03 06:05 UTC, Noma9363 commented on src/components/layout/header/category/styles/CategoryHeader.module.scss
> +        .list_item_icon{
따로 규격을 정하겠음

2024-02-05 08:13 UTC, KimEuiSoo commented on src/components/layout/header/gnb/gnbMain/GnbMain.tsx
> +                    'Authorization-Mac': '00-A5-54-E3-83-AC',
저거 gql 테스트 때문에 넣어둔거라 빼는걸 까먹음 다시 빼놓을게

2024-02-05 08:59 UTC, KimEuiSoo commented on src/components/layout/header/category/CategoryHeader.tsx
> +import clsN from 'classnames';
지금 atom부터 시작해서 전체적으로 clsN으로 통일되어 있어서 이건 이대로 진행될거 같음

2024-02-09 09:23 UTC, Hangeulkim approved these changes

2024-02-10 00:51 UTC, Noma9363 approved these changes
BEM 네이밍을 활용

조만간 craco.config.js 를 통해 css 로더 모듈을 추가할 필요가 있음

2024-02-10 00:54 UTC, merged