Feature/login
S-OSTeam/shop-web pull request #16
Opened 2024-02-19 06:31 UTC by cywin1018

# 작업사항
- 로그인 부분 웹, 모바일 만듦
- 디자인만 적용하였고, 실제 동작은 아직
- rebase 나중에 받아서 scss 부분 수정한 후 기능 추가 할게
- 지적할만한 내용 많을지도.. 다양한 욕과 지적 환영

2024-02-20 06:51 UTC, KimEuiSoo reviewed
쓸모없는 주석 삭제 해주세요.

2024-02-20 06:56 UTC, KimEuiSoo reviewed
모바일 로그인을 따로 만들어서 재활용하지 않고 재 랜더링을 계속 받는게 문제입니다.
따로 모바일 로그인을 만들지 말고 반응형 디자인으로 로그인 화면 하나에서 hook에 있는 useDomSizeCheck으로 판단하여 컴포넌트를 적용 시킵시다

2024-02-20 06:58 UTC, Noma9363 commented on src/asset/image/icons/GoogleIcon.svg
https://butsteadily.tistory.com/16

위 링크를 참고 부탁드리옵니다.
![Uploading sociallogin.jpg…]()

2024-02-20 06:58 UTC, Noma9363 commented on src/asset/image/icons/KakaoIcon.svg
https://butsteadily.tistory.com/16
![Uploading sociallogin.jpg…]()

2024-02-20 06:58 UTC, Noma9363 commented on src/asset/image/social/GoogleLogin.svg
로그인 아이콘 영역 svg만 활용하고 나머지는 직접 만들어 봅시다..!

2024-02-20 06:58 UTC, Noma9363 commented on src/asset/image/social/KakaoLogin.svg
로그인 아이콘 영역 svg만 활용하고 나머지는 직접 만들어 봅시다..!

2024-02-20 06:58 UTC, Noma9363 commented on src/asset/image/social/NaverLogin.svg
로그인 아이콘 영역 svg만 활용하고 나머지는 직접 만들어 봅시다..!

2024-02-26 06:27 UTC, Noma9363 commented on src/components/organisms/login/login/style/style.module.scss
> +    .save-id{
add &__ plz

2024-02-26 06:28 UTC, Noma9363 commented on src/components/organisms/login/login/style/style.module.scss
> +
sass(scss) 객체 진입은 최대 3개로 하도록 합시다.

2024-02-26 06:32 UTC, Noma9363 commented on src/components/organisms/login/social/SocialLogin.tsx
> +                    <Box className={clsN(`${style['mobile-social-login-wrapper']}`)}>
하나의 몰큘로 만듭시다.

2024-02-26 06:34 UTC, Noma9363 commented on src/components/organisms/login/social/SocialLogin.tsx
> +                    </Box>
해당 버튼들을 생성하고 감싸는 몰큘즈로 만들어봅시다...
<IconBtnGenerator 라던가 등등...

2024-02-26 06:35 UTC, Noma9363 commented on src/components/organisms/login/social/SocialLogin.tsx
> +                    </Box>
해당 버튼들을 생성하고 감싸는 몰큘즈로 만들어봅시다...
<IconBtnGenerator 라던가 등등...

2024-02-26 06:37 UTC, Noma9363 commented on src/components/templates/LoginForm/LoginForm.tsx
> +                <>
<></> 빈 태그와, React.fragment 이것도 안됨
div 혹은 box 요소 태그를 사용합시다.

2024-02-26 06:59 UTC, KimEuiSoo commented on src/custom.d.ts
> +  export const ReactComponent: React.FC<React.SVGProps<SVGSVGElement>>;
svg 파일을 asset으로 가져오지 말고 다운받은 파일 메모장이나 vscode로 실행시켜서 코드 그대로 붙이면 됩니다.

2024-02-26 06:59 UTC, KimEuiSoo commented on src/components/molecules/checkbox/saveId/SaveId.tsx
> +export default SaveId;
molecules는 재활용성 떄문에 하나만 쓰이면 molecules가 아닌 organism에 molecules+atom으로 구조를 짜는게 더 효율적일거 같습니다.

2024-02-26 06:59 UTC, KimEuiSoo commented on src/components/molecules/divider/dividerWithText/DividerWithText.tsx
> +const DividerWithText: React.FC<DividerWithTextProps> = ({ children, ...textProps }) => {
위에 구조처럼 하지 마시고 ({...props}: DividerWithTextProps) 이런식으로 적용하시면 밑에 props.children과 TextProps의 Element까지 사용가능합니다.

2024-03-03 11:37 UTC, Noma9363 commented on src/asset/image/social/KakaoLogin.svg
를 직접 컴포넌트로 만들어 봅시다

2024-03-03 11:37 UTC, Noma9363 commented on src/asset/image/social/GoogleLogin.svg
를 직접 컴포넌트로 만들어 봅시다

2024-03-03 11:37 UTC, Noma9363 commented on src/asset/image/social/NaverLogin.svg
를 직접 컴포넌트로 만들어 봅시다

2024-03-03 11:38 UTC, Noma9363 commented on src/components/molecules/button/imageButton/ImageButton.tsx
> +    img: React.ReactNode;
이미지 패스를 줄 것인지 아니면 이미지를 줄 것인지
아니면 그 어... React.reactNode 는 모든 타입을 받아드리므로 타입을 검증하는 다른 방식을 찾아야 할듯

2024-03-03 11:39 UTC, Noma9363 commented on src/components/molecules/button/imgTextButton/ImgTextButton.tsx
> +    img: React.ReactNode;
이미지 패스를 줄 것인지 아니면 이미지를 줄 것인지
아니면 그 어... React.reactNode 는 모든 타입을 받아드리므로 타입을 검증하는 다른 방식을 찾아야 할듯

2024-03-03 11:42 UTC, Noma9363 commented on src/components/organisms/login/login/Login.tsx
> +                    />
여러곳에 사용할 것 처럼 보이는 인풋이나 버튼 영역들을 몰큘즈 컴포넌트로 만들어봅시다.

![image](https://github.com/S-OSTeam/shop-web/assets/69139078/09c66ed3-ca06-4740-996e-575a3082154b)

2024-03-03 11:44 UTC, Noma9363 commented on src/components/organisms/login/saveId/SaveId.tsx
이 부분은 몰큘 영역으로 정하고 올가니즘에 불러와 관리하면 될듯합니다.

2024-03-03 11:45 UTC, Noma9363 commented on src/custom.d.ts
> +  export const ReactComponent: React.FC<React.SVGProps<SVGSVGElement>>;
FC 쓰지마!!!!!!!!!!!!!!!!!!!!!!!!!!

2024-05-29 08:34 UTC, Noma9363 requested changes
일단은 먼저 로그인 관련 컴포넌트에서 
여러 아톰 컴포넌트를 활용하는데 중복되거나 
모듈화가 되지 않는점이 있습니다.

컴포넌트를 한번 더 다시 모듈화 체크를 하면 좋아질 듯 합니다.

2024-05-29 08:34 UTC, Noma9363 commented on src/components/organisms/login/login/Login.tsx
컴포넌트 내부 요소들을 한눈에 알아보기가 힘든점이 있습니다.

이거를 아래처럼
```
// 텍스트 필드 컴포넌트에 맞도록 onChange 속성 제너릭 처리
    const handleInputChange = <T extends HTMLInputElement | HTMLTextAreaElement>(event: React.ChangeEvent<T>) => {
        const { name, value } = event.target;
        setFormData({
            ...formData,
            [name]: value,
        });
    };

    /* JSX 컴포넌트 */
    // 모바일 로그인 타이틀 영역
    const MobTitleArea = (
        <Box className={clsN(`${style['mobile-login-wrapper__title']}`)}>
            <Divider variant="middle" textAlign="center">
                또는
            </Divider>
        </Box>
    );
    // 모바일 버튼그룹 영역
    const MobLoginBtnGroup = (
        <Box className={clsN(`${style['mobile-login-wrapper__btn-wrapper']}`)}>
            <Button
                className={clsN(`${style['mobile-login-wrapper__btn-wrapper__signup-btn']}`)}
                variant="outlined"
            >
                회원가입
            </Button>
            <Button className={clsN(`${style['mobile-login-wrapper__btn-wrapper__login-btn']}`)} variant="outlined">
                로그인
            </Button>
        </Box>
    )
    
    // 모바일 사이즈 로그인 form
    const LoginMobileForm = (
        <Box className={clsN(`${style['mobile-login-wrapper']}`)}>
            {MobTitleArea}
            {MobLoginBtnGroup}
        </Box>
    );
```

모듈화 하면서 아톰이 뭉쳐있으면 몰큘로 따로 제작하는것도 좋아보입니다.

2024-05-29 08:34 UTC, Noma9363 commented on src/components/organisms/login/login/style/style.module.scss
> +.mobile-login-wrapper{
해당 wrapper 키워드 때문에 클래스명이 길어지는 경우가 있어 
그냥 wrapper 를 빼고 앞에 mobile-... 클래스명을 사용해도 됨

2024-05-29 08:34 UTC, Noma9363 commented on src/components/organisms/login/social/SocialLogin.tsx
각각의 컴포넌트 마다 어떠한 기능과 역할을 가지고 있는지 알아보기 위해 모듈화를 해봅시다

2024-07-09 13:59 UTC, Noma9363 reviewed
type 인터페이스와
함수형 프로그래밍 수정 확인

2024-08-09 07:22 UTC, closed without merging