Feature/home
S-OSTeam/shop-web pull request #21
Opened 2024-03-01 09:01 UTC by KimEuiSoo

feature: home 화면 작업
refactor: swiper 커스텀 pagination 및 freeMode 추가

2024-03-01 09:16 UTC, Noma9363 reviewed
폰트사이즈나 색상 패딩, 마진값 수치 배리어블 스타일 빠르게 만들어놓고 있겠으

2024-03-01 09:21 UTC, cywin1018 approved these changes

2024-03-06 08:40 UTC, Hangeulkim requested changes

2024-03-06 08:40 UTC, Hangeulkim commented on src/components/organisms/home/product/recommend/Recommend.tsx
> +                slidesPerView={4}
이것도 반응형 처리 필요

2024-04-05 04:08 UTC, Noma9363 reviewed
주석 부타드리와요..!

2024-04-05 04:08 UTC, Noma9363 commented on src/components/molecules/icon/IconGroup.tsx
주석 부타드리와요..!

2024-04-05 04:08 UTC, Noma9363 commented on src/components/molecules/text/textGroup/TextGroup.tsx
주석 부타드리와요..!

2024-05-29 09:14 UTC, Noma9363 reviewed
propTypes 는 타입스크립트에 사용하지 않아도 됨.
겹치는 컴포넌트는 따로 분리해보기
폰트 사이즈는 금욜날 제가 빠르게 공지하것습니다..!

2024-05-29 09:14 UTC, Noma9363 commented on src/components/molecules/text/textGroup/TextGroup.tsx
> +        if (textData === undefined || textData[index] === undefined) {
윗분 뭐라하는지 이해를 못했어요

연산자의 공백을 쓰지말라는건지
(textData === undefined) => (textData===undifined)

아니면 textData.?[index] 이런거 말하는건지

2024-05-29 09:14 UTC, Noma9363 commented on src/components/organisms/home/Review/ReviewList.tsx
> +                            <Text className={clsN(styles['review-wrapper__review-move'])} text="해당 상품 바로가기" />
<Title><Text> 겹치는 부분을 모듈화해봅시다

2024-05-29 09:14 UTC, Noma9363 commented on src/components/organisms/home/Review/styles/ReviewList.module.scss
> +.review-wrapper{
wrapper 가 긴 경우 제외해도 됨

2024-05-29 09:14 UTC, Noma9363 commented on src/components/organisms/home/Review/styles/ReviewList.module.scss
> +    font-size: 32px;
폰트사이즈는 
`$font-size-map: ...` 활용하기

2024-06-03 08:29 UTC, KimEuiSoo commented on src/components/molecules/text/title/Title.tsx
> +    content: '',
에러 때문은 아니고 처음부터 저런 형식으로 해서 계속 저런 방식으로 처리함

2024-06-03 08:30 UTC, KimEuiSoo commented on src/pages/home/DeamHomePage.tsx
> +            console.log(itemData);
네~

2024-06-03 08:31 UTC, KimEuiSoo commented on src/components/organisms/home/Review/styles/ReviewList.module.scss
> +.review-wrapper{
그건 협의해서 맞춰야 될듯

2024-06-03 08:32 UTC, KimEuiSoo commented on src/components/organisms/home/Review/styles/ReviewList.module.scss
> +    font-size: 32px;
네

2024-06-07 12:00 UTC, KimEuiSoo commented on src/components/molecules/text/textGroup/TextGroup.tsx
> +        if (textData === undefined || textData[index] === undefined) {
undifined 처리 해둠

2024-07-05 01:25 UTC, merged