Feature/inquiry 관리자 공지사항 템플릿 페이지
S-OSTeam/shop-web pull request #38
Opened 2024-08-19 07:04 UTC by Noma9363

feature : inquiry 공지사항 템플릿 컴포넌트

- Notice.tsx : 공지사항 템플릿 페이지로 데이터를 날짜, 키워드, 등록 상태에 따라 데이터 검색 가능
- CollapseForm : 이전에 template 내부에 TSX 로 만드는걸 따로 분리
- DateRange : 버튼 입력과 인자로 받은 속성값에 따라 날짜 변경 및 스타일 수정

관리자의 공지사항 페이지로 리코일과 속성상속을 통해 상태관리를 하며 검색을 하는 페이지 제작

2024-08-20 04:44 UTC, cywin1018 approved these changes

2024-08-20 06:54 UTC, KimEuiSoo commented on src/recoil/atoms/admin/inquiry/notices/noticesFilterAtom.ts
> +    postStatus: '전체' | '공개' | '비공개';
보통 한글 보단 영어를 선호 합니다
UTF-8때문에 나중에 한글은 깨짐 현상이 발생을 일으킬 수도 있어서 문제가 발생 할 수 있으니 다시 위에꺼가 더 좋아 보입니다.

2024-08-20 06:54 UTC, KimEuiSoo commented on src/components/templates/inquiry/notices/Notices.tsx
> +    /* 규모가 너무 큰 렌더링 방식임 수정 고려중 */
수정 고려 중인 문구 같은 것은 TODO 주석으로 입력 부탁드립니다.

2024-08-20 06:54 UTC, KimEuiSoo commented on src/components/templates/inquiry/notices/Notices.tsx
> +    const noticesStorage: NotificationProps[] = [];
임시로 데이터를 넣어 놓기 위해서는 NotificationProps의 Empty를 만들어서 빈 타입으로 만드는것이 좋거난 아니면 empty.list 이런 방식으로 코딩하는 것이 버그를 유발 하지 않습니다.

2024-08-20 06:54 UTC, KimEuiSoo commented on src/components/templates/inquiry/notices/Notices.tsx
> +    };
해당 input 같은 데이터를 입력 하는 이벤트를 쓸 때에는 계속해서 데이터 값이 바뀌므로 리렌더링을 값이 바뀔 떄 마다 발생하는걸 염두하고서 다른 코드들의 최적화를 신경쓰고 조심히 써야 합니다 만약 그렇게 처리를 못할거 같으면 따로 빼서 쓰느것도 하나의 방법이라고 할 수는 있습니다.

2024-08-20 06:54 UTC, KimEuiSoo commented on src/components/templates/inquiry/faq/Faq.tsx
> +    ];
typescript의 장점은 타입을 명시에서 보다 편리하게 다른 파트의 팀원에게 공유가 가능하다는 장점을 가지고 있습니다. 근데 javadoc처럼 쓰면서 주석을 달면 typescript의 장점이 많이 퇴색되는거 같습니다.

2024-08-20 06:54 UTC, KimEuiSoo commented on src/components/organisms/collapsedListResult/collapsedListResult.tsx
> +            arr.map((_val, _idx) => (_idx === _index ? !_val : _val));
보통적으로 _를 앞에 쓰는것은 지향하지 않습니다 뺴주세요.

2024-08-20 06:54 UTC, KimEuiSoo commented on src/components/organisms/admin/searchBar/SearchBar.tsx
> +};
interface가 아닌 타입으로 적용한 이유가 있나요? 궁금합니다.

2024-08-20 06:54 UTC, KimEuiSoo commented on src/components/organisms/admin/filteredSearch/FilteredSearch.tsx
> +    onSearch: (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => void;
보통적으로 inputElement만 씁니다
TextAreaElement는 html 태그중에 TextArea 태그를 가리킬때만 쓰입니다.
불필요한 요소 같아서 말해봅니다.

2024-08-20 06:54 UTC, KimEuiSoo commented on src/components/molecules/dateRange/DateRange.tsx
>          // 아래 수행할 함수 실행
77번쨰 줄에 case null:과 case -1: 를 줄만 바꿔 쓰고 바로 밑에 break를 걸면 두개가 공통적인 작업을 하므로 코드적인 가독성이 올라갑니다.
 그리고 리코일이나 무엇을 갱신할 때는 의존성 배열을 입력받는 useMemo를 이용해서 리렌더링이 발생하여 버그가 발생해 버그가 발생할 확률을 줄여줍시다.

2024-08-20 06:54 UTC, KimEuiSoo commented on src/routes/adminRouter/AdminRouter.tsx
>          </Routes>
adminRouter를 만드실거면 공용으로 사용되는 주소이기 때문에 주소를 한번에 바꿔야 하는 상황이 발생하는 상황에서는 일일히 바꿔주는 일보다는 util이라는 공용적인 변수로 만들어서 처리 해주는 편이 더욱 간편할 거 같습니다. 
```suggestion
        </Routes>
```

2024-08-20 06:58 UTC, KimEuiSoo reviewed
전반적으로 조금씩 고칠게 보입니다.

2024-08-20 07:04 UTC, Noma9363 commented on src/recoil/atoms/admin/inquiry/notices/noticesFilterAtom.ts
> +    postStatus: '전체' | '공개' | '비공개';
속성 값 매핑 메모...!

2024-08-20 07:04 UTC, KimEuiSoo requested changes
전반적으로 고칠 것이 보이지만 잘 짜셨습니다. 수고하셨습니다.
코멘트 남긴 부분들 확인 후에 고쳐 주세요.

2024-08-20 07:04 UTC, KimEuiSoo commented on src/routes/adminRouter/AdminRouter.tsx
>          </Routes>
라우터에 등록된 Admin 주소들도 util 쪽으로 변수형태로 분리시켜 관리 시키면 나중에 유지보수하면서 편리하게 관리 하실 수 있습니다.

2024-08-20 07:06 UTC, Noma9363 commented on src/components/templates/inquiry/notices/Notices.tsx
> +    const noticesStorage: NotificationProps[] = [];
빈 배열 메모

2024-08-20 07:07 UTC, Noma9363 commented on src/components/templates/inquiry/notices/Notices.tsx
> +    };
`useMemo` 혹은 콜백 찾아보겠습니다.

2024-08-20 07:08 UTC, Noma9363 commented on src/components/templates/inquiry/faq/Faq.tsx
> +    ];
엇

2024-08-20 07:08 UTC, Noma9363 commented on src/components/organisms/collapsedListResult/collapsedListResult.tsx
> +            arr.map((_val, _idx) => (_idx === _index ? !_val : _val));
언더바 제거하는걸로

2024-08-20 07:14 UTC, Noma9363 commented on src/components/organisms/admin/searchBar/SearchBar.tsx
> +};
인도형님들의 Mui 커스텀 예시가 오래된거였군요 인터페이스로 수정하겠습니다...!

2024-08-20 07:17 UTC, Noma9363 commented on src/components/organisms/admin/filteredSearch/FilteredSearch.tsx
> +    onSearch: (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => void;
`HTMLTextAreaElement` 이벤트를 제거하겠습니다!

2024-08-20 07:22 UTC, Noma9363 commented on src/components/molecules/dateRange/DateRange.tsx
>          // 아래 수행할 함수 실행
```
    // Dayjs 스왑 이벤트
    const fixDateState = (compare: number | null) => {
        switch (compare) {
            case null:
                break;
            case -1:
                // 인자1 이 인자2 보다 작음
                break;
            case 0: {
                // 종료일 찾기 // 인자중 하나라도 null 인 상황, 그 중 큰값은 endD 로 정하기 -1 까지 조회하도록 하기
                const tempEndDate = fromD?.isAfter(endD) ? fromD : endD;
                // 널 병합 연산자 (??) 를 사용해서 undefined 발생할 경우 방지하기
                const tempStartDate = tempEndDate?.subtract(1, 'day') ?? null;
                // 상태 갱신
                setFromD(tempStartDate);
                setEndD(tempEndDate);
                break;
            }
            case 1: {
                // 인자1 이 인자2 보다 큼
                const tempLastDate = fromD;
                setFromD(endD);
                setEndD(tempLastDate);
                break;
            }
            default:
                break;
        }
    };
```

- DateRange.tsx line:77
- case: null, -1 순서만 바꾸고 break 걸기
- 리코일 혹은 상태를 갱신할때 의존성 배열을 입력받는 `useMeno` 를 이용해 리렌더링 버그 방지하기

메모...!

2024-08-20 07:22 UTC, Noma9363 commented on src/routes/adminRouter/AdminRouter.tsx
>          </Routes>
해당 라우터 유틸폴더로 관리하기...메모...

나는 아직...배가 고프다...

2024-08-22 08:25 UTC, KimEuiSoo requested changes
고칠것이 계속 보이긴 하지만 좋아진 부분도 많이 보입니다.
고생하셨습니다.
코멘트 남겨놓은 부분 확인해 보시고 수정 후 resolve 누르시기 바랍니다.

2024-08-22 08:25 UTC, KimEuiSoo commented on src/components/organisms/collapsedListResult/collapsedListResult.tsx
>  interface CollapsedTableClasses {
인터페이스를 모아쓸거면 interface 폴더에서 모아두고 export로 가져와서 씁시다.
너무 한쪽어 interface가 모아져있으면 나중에 같은 동일한 parameter를 가지고 있는 interface가 있는데 구분을 하지 못하고 코드의 가독성을 뺏을 뿐만 아니라 유지보수에도 큰 장애를 가져옵니다.

2024-08-22 08:25 UTC, KimEuiSoo commented on src/components/organisms/collapsedListResult/collapsedListResult.tsx
> +            arr.map((val, idx) => (idx === index ? !val : val));
arr.map() 함수는 배열의 모든 요소를 순회하며 새로운 배열을 만들어 배열의 길이가 길어질수록 성능 저하가 일어 날 수 있습니다. 그렇기 때문에 이런식으로 바꿔보는건 어떤가요?
const toggleCollapse = (index: number, arr: boolean[]): boolean[] => {
    const data = [...arr];
    data[index] = !data[index];
    return data;
};

2024-08-22 08:25 UTC, KimEuiSoo commented on src/components/templates/product/prodmgt/Prodmgt.tsx
> +export const ProdmgtTemplate = () => {
줄여쓰지 마세요 ProductManagerTagble

2024-08-22 08:25 UTC, KimEuiSoo commented on src/components/templates/inquiry/notices/Notices.tsx
> +    const noticesStorage: EmptyNoticationProps[] = [];
Empty 타입 객체는 보통 해당 interface가 있는 위치에 있거나 Empty 데이터 값에 넣어 둡니다.

2024-08-22 08:25 UTC, KimEuiSoo commented on src/components/templates/inquiry/notices/Notices.tsx
> +    const tDataConvert = filteredNtcItems.slice(tPage * rowPerPage, tPage * rowPerPage + rowPerPage).map((item) => {
이런 계산식을 하는 format은 함수로 빼고서 계산을 마친 후에 slice 해주고서 그 아이템을 map을 해줍시다.
const itemSlice=(인자 값 1, 인자 값 2)=>{
     return item.slice(인자값 1, 인자 값2) 
}
이런 방식으로 하면 코드의 가독성이 올라가고 만약 해당 함수의 commaFormat 처럼 컴마를 찍어주는 함수와 같이 재활용성이 올라가면 util/common으로 빼서 해당 함수를 Common.ts에 함수를 넣고 export로 함수를 호출하여 사용할 수도 있습니다.

2024-08-22 09:21 UTC, Noma9363 commented on src/components/templates/inquiry/faq/Faq.tsx
> +    ];
해당 Faq 템플릿 컴포넌트로 출력 테스트를 위해 사용되어 임시로 넣었으나

추후에 다른컴포넌트 작업할경우 주의하면서 작성하겠습니다.

2024-08-22 09:24 UTC, Noma9363 commented on src/components/molecules/admin/notice/collapseForm/CollapseForm.tsx
> +    imgUrls?: string[];
공지사항의 경우 이미지없이 본문만 적는 공지사항의 경우도 있어 `undefined` 로 하였으나 해당부분은 @KimEuiSoo 와 함께 논의해 보겠습니다.

- 광고 이미지
- 기타 디폴트 이미지

2024-08-27 09:50 UTC, KimEuiSoo requested changes

2024-08-27 09:50 UTC, KimEuiSoo commented on src/components/molecules/dateRange/DateRange.tsx
> +    const compareDate = (date1: Dayjs | null, date2: Dayjs | null): number | null => {
null 대신 undefined로 적용시켜도 되면 undefined로 적용시키는게 타입스크립트에서는 좋습니다.

2024-08-27 11:13 UTC, Hangeulkim requested changes

2024-08-27 11:13 UTC, Hangeulkim commented on src/components/templates/inquiry/notices/Notices.tsx
> +    const debounceSearchValue = useDebounce(searchVal, 200);
ms 단위 입니다 이건 0.2초 일텐데

2024-10-11 12:47 UTC, merged